### ISSUE TITLE
Refactor chainstore to be based on context.Context

### ISSUE THREAD

**Issue by pkieltyka** [pressly/chainstore#8]
Each chainstore action should be based on a context.Context request context. The benefit here is a request chain can be cancelled with a timeout or cancel function. I've found in imgry that this can be useful in case some requests take to long to complete and instead the goroutine never finishes.

It will make for a much more robust store.

**Comment by pkieltyka** [comment]
btw, as part of this, let's remove goconvey from the tests and use https://github.com/stretchr/testify instead

**Comment by xiam** [comment]
Closed by https://github.com/pressly/chainstore/issues/9
